spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  application:
    name: local-grpc-server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

grpc:
  server:
    port: 9898
mybatis:
  type-aliases-package: com.tobacco.generator.entities,com.tobacco.entities
  mapper-locations: classpath*:generator-mapper/*.xml



